# Generated by Django 5.2.7 on 2025-10-07 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("spaces", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpaceMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Inactive"), (2, "Actived"), (3, "Suspended")],
                        default=1,
                    ),
                ),
                ("joined_date", models.DateField(blank=True, null=True)),
                ("expired_date", models.DateField(blank=True, null=True)),
                ("available_start_time", models.DateTimeField(blank=True, null=True)),
                ("available_end_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="spaces.space",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="space_memberships",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "ordering": ["joined_date"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="space_membe_status_93d331_idx"
                    )
                ],
                "unique_together": {("user", "space")},
            },
        ),
    ]
