# Generated by Django 5.2.7 on 2025-10-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("space_members", "0002_spacemember_deleted_spacemember_deleted_by_cascade"),
        ("spaces", "0003_space_deleted_space_deleted_by_cascade"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="spacemember",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="spacemember",
            name="active_flag",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name="spacemember",
            unique_together={("user", "space", "active_flag")},
        ),
    ]
