# Generated by Django 5.2.7 on 2025-10-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.TextField()),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Registered"), (2, "Actived"), (3, "Deactivated")],
                        default=1,
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                (
                    "confirmation_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("confirmation_sent_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reset_password_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("reset_password_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["username"], name="users_user_usernam_65d164_idx"
                    ),
                    models.Index(fields=["email"], name="users_user_email_6f2530_idx"),
                    models.Index(
                        fields=["status"], name="users_user_status_07d06d_idx"
                    ),
                    models.Index(
                        fields=["confirmation_token"],
                        name="users_user_confirm_c3f1ac_idx",
                    ),
                    models.Index(
                        fields=["reset_password_token"],
                        name="users_user_reset_p_d96431_idx",
                    ),
                ],
            },
        ),
    ]
