# Generated by Django 5.2.7 on 2025-10-08 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("spaces", "0003_space_deleted_space_deleted_by_cascade"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Pending"),
                            (2, "Completed"),
                            (3, "Failed"),
                            (4, "Refunded"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "payment_method",
                    models.IntegerField(
                        choices=[
                            (1, "Credit Card"),
                            (2, "PayEasy"),
                            (3, "Convenience Store"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "payment_type",
                    models.IntegerField(
                        choices=[(1, "New"), (2, "Renewal")], default=1
                    ),
                ),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="spaces.space"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
            options={
                "ordering": ["-payment_date"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="payment_his_status_fe937f_idx"
                    ),
                    models.Index(
                        fields=["payment_method"], name="payment_his_payment_00c8bf_idx"
                    ),
                    models.Index(
                        fields=["payment_type"], name="payment_his_payment_af0b05_idx"
                    ),
                ],
            },
        ),
    ]
