# Generated by Django 5.2.7 on 2025-10-07 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("spaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpacePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_type",
                    models.IntegerField(
                        choices=[(1, "Hourly"), (2, "Daily"), (3, "Monthly")], default=1
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=0, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="spaces.space"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["space"], name="space_price_space_i_96b5d0_idx"
                    ),
                    models.Index(
                        fields=["price_type"], name="space_price_price_t_f116ae_idx"
                    ),
                ],
                "unique_together": {("space", "price_type")},
            },
        ),
    ]
