# Generated by Django 5.2.7 on 2025-10-27 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("space_prices", "0002_spaceprice_deleted_spaceprice_deleted_by_cascade"),
        ("spaces", "0003_space_deleted_space_deleted_by_cascade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spaceprice",
            name="space",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="space_prices",
                to="spaces.space",
            ),
        ),
    ]
