# Generated by Django 5.2.7 on 2025-10-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amenities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="amenity",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="amenity",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
