# Generated by Django 5.2.7 on 2025-10-07 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("working_spaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Space",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Waiting"), (2, "Activated"), (3, "Blocked")],
                        default=1,
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "Private Office"),
                            (2, "Meeting Room"),
                            (3, "Hot Desk"),
                        ],
                        default=1,
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("capacity", models.IntegerField()),
                ("location_map", models.JSONField(default=dict)),
                ("description", models.TextField(blank=True, null=True)),
                ("open_time", models.TimeField()),
                ("close_time", models.TimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "working_space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spaces",
                        to="working_spaces.workingspace",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(fields=["name"], name="spaces_spac_name_88de59_idx"),
                    models.Index(
                        fields=["status"], name="spaces_spac_status_c51728_idx"
                    ),
                    models.Index(fields=["type"], name="spaces_spac_type_43341d_idx"),
                ],
            },
        ),
    ]
