# Generated by Django 5.2.7 on 2025-10-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spaces", "0001_initial"),
        ("working_spaces", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="space",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="space",
            unique_together={("working_space", "name")},
        ),
    ]
