# Generated by Django 5.2.7 on 2025-10-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spaces", "0002_alter_space_name_alter_space_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="space",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
