# Generated by Django 5.2.7 on 2025-10-08 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("space_bookings", "0002_spacebooking_deleted_spacebooking_deleted_by_cascade"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="spacebooking",
            unique_together=set(),
        ),
    ]
