# Generated by Django 5.2.7 on 2025-10-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("working_spaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workingspace",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="workingspace",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
